using System.Globalization;

namespace Jellyfin.Plugin.MediathekViewDL;

/// <summary>
/// Contains global constants for the plugin.
/// </summary>
public static class Constants
{
    /// <summary>
    /// The Category for the Scheduled Tasks of this Plugin.
    /// </summary>
    public const string SchedTaskCat = "Mediathek Downloader (CuriousApe2020 Fork)";

    /// <summary>
    /// The prefix for channel IDs of channels provided by this plugin.
    /// </summary>
    public const string ChannelIdPrefix = "MediathekViewDL-Zapp-";

    /// <summary>
    /// The format string for generating the key of a scheduled task. The actual key will be generated by appending a specific identifier to this prefix.
    /// </summary>
    /// <param name="key">The Key without prefix.</param>
    /// <returns>Key with prefix.</returns>
    public static string GetSchedTaskKey(string key)
    {
        return $"MediathekViewDL-{key}";
    }
}
